# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        script: ["./install.sh linux", "./link.sh"]
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run ${{matrix.script}}
        run: ${{matrix.script}}
        
      - name: Run zsh
        run: zsh
        
      # Error Check
      - name: Run install.sh
        run: ./install.sh linux

      - name: Run link.sh
        run: ./link.sh
        
      - name: Run zsh
        run: zsh
          
  setup_mac:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    strategy:
      fail-fast: false
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Error Check
      - name: Run install.sh
        run: ./install.sh mac

      - name: Run link.sh
        run: ./link.sh
        
      - name: Run zsh
        run: zsh
